title: Minimal theme Data Scientist Albarey22 Albarey33 reviewed 3:46 PM
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages. # comment not visible
<br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
